//
// Created by Luka Dulčić on 05/01/2018.
//

#ifndef BIOINFORMATICS_PATTERN_PARSE_H
#define BIOINFORMATICS_PATTERN_PARSE_H

#define SIGMA 128
#define MAX_BUF 2048
uint64_t ONE = 1;

#endif //BIOINFORMATICS_PATTERN_PARSE_H
